apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicaCount }}  # количество реплик
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: {{ .Values.app.image }}:{{ .Values.app.tag }}  # Образ приложения из локального репозитория k8s
        ports:
        - containerPort: 8080  # Порт, на котором работает приложение
---
apiVersion: v1
kind: Service
metadata:
  name: calendar-app-service
spec:
  type: ClusterIP  # Внутренний сервис для общения внутри кластера
  ports:
  - port: 80       # Внешний порт
    targetPort: 8080  # Порт контейнера
  selector:
    app: {{ .Values.app.name }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calendar-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: my-calendar-app.local  # Домен для приложения
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: calendar-app-service
            port:
              number: 80
