apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.goose.name }}
  labels:
    app: {{ .Values.goose.name }}
spec:
  template:
    metadata:
      labels:
        app: {{ .Values.goose.name }}
    spec:
      containers:
      - name: goose
        image: {{ .Values.goose.image }}:{{ .Values.goose.tag }}
        imagePullPolicy: IfNotPresent
        command:
        - goose
        - -dir=/migrations
        - postgres
        - "host=postgres-service port=5437 user=postgres password=postgres dbname=postgres sslmode=disable search_path=public"
        - up
        volumeMounts:
        - name: migrate-volume
          mountPath: /migrations
      volumes:
      - name: migrate-volume
        configMap:
          name: migrations
      restartPolicy: Never
  backoffLimit: 4