apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    app: {{ .Values.postgres.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Объем дискового пространства
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres.name }}
  labels:
    app: {{ .Values.postgres.name }}
spec:
  replicas: {{ .Values.postgres.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.postgres.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.name }}
    spec:
      containers:
      - name: {{ .Values.postgres.name }}
        image: {{ .Values.postgres.image }}:{{ .Values.postgres.tag }}  # Используется официальный образ PostgreSQL
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "postgres"  # Имя пользователя для подключения
        - name: POSTGRES_PASSWORD
          value: "postgres"  # Пароль пользователя
        - name: POSTGRES_DB
          value: "postgres"  # Имя базы данных
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: ClusterIP  # Внутренний сервис для взаимодействия
  ports:
  - port: 5437       # Внешний порт
    targetPort: 5432  # Порт контейнера
  selector:
    app: {{ .Values.postgres.name }}
