apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
  labels:
    app: {{ .Values.rabbit.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Объем дискового пространства
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.rabbit.name }}
  labels:
    app: {{ .Values.rabbit.name }}
spec:
  replicas: {{ .Values.rabbit.replicaCount }}  # RabbitMQ запускается в одном экземпляре для базового использования
  selector:
    matchLabels:
      app: {{ .Values.rabbit.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.rabbit.name }}
    spec:
      containers:
      - name: {{ .Values.rabbit.name }}
        image: {{ .Values.rabbit.image }}:{{ .Values.rabbit.tag }}  # Образ RabbitMQ с панелью управления
        ports:
        - containerPort: 5672  # Порт для подключения клиентов (AMQP)
        - containerPort: 15672  # Порт для веб-интерфейса управления
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "user"  # Имя пользователя
        - name: RABBITMQ_DEFAULT_PASS
          value: "password"  # Пароль пользователя
        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq-storage
      volumes:
      - name: rabbitmq-storage
        persistentVolumeClaim:
          claimName: rabbitmq-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  type: ClusterIP
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
  - name: management
    port: 15672
    targetPort: 15672
  selector:
    app: {{ .Values.rabbit.name }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: rabbitmq.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rabbitmq-service # Важно! Тут должно быть указано название сервиса, чтобы ingress его смог найти
            port:
              number: 15672