apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.sender.name }}
  labels:
    app: {{ .Values.sender.name }}
spec:
  replicas: {{ .Values.sender.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.sender.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.sender.name }}
    spec:
      containers:
      - name: {{ .Values.sender.name }}
        image: {{ .Values.sender.image }}:{{ .Values.sender.tag }}
        ports:
        - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: message-consumer-service
spec:
  selector:
    app: {{ .Values.sender.name }}
  ports:
    - protocol: TCP
      port: 81
      targetPort: 8081
  type: ClusterIP
