postgres:
  name: postgres
  replicaCount: 1
  image: postgres
  tag: 14.4

goose:
  name: goose-migrator
  replicaCount: 1
  image: gomicro/goose
  tag: latest

app:
  name: calendar-app
  replicaCount: 1
  image: my-calendar-app
  tag: 1.0.0

rabbit:
  name: rabbitmq
  replicaCount: 1
  image: rabbitmq
  tag: 3-management

scheduler:
  name: message-producer
  replicaCount: 1
  image: message-producer
  tag: 1.0.0

sender:
  name: message-consumer
  replicaCount: 1
  image: message-consumer
  tag: 1.0.0
