duration = "120s"

[logger]
level = "DEBUG"
out_paths = ["stdout"]
err_paths = ["stderr"]

[database]
inmemory=false
driver = "postgres"
# host = "localhost"
host = "postgres-service"
# port = "5432"
port = "5437"
db = "postgres"
user = "postgres"
password = "postgres"
ssl = "disable"

[rmq]
host = "localhost"
port = "5672"
protocol = "amqp"
username = "guest"
password = "guest"
exchange = "test-exchange"
queue = "test-queue"
