[logger]
level = "INFO"

[app.http_server]
host = "0.0.0.0"
port = "8080"

[app.grpc_server]
host = "0.0.0.0"
port = "8081"

[app.database]
inmemory=false
driver = "postgres"
# host = "localhost"
host = "postgres-service"
# port = "5432"
port = "5437"
db = "postgres"
user = "postgres"
password = "postgres"
ssl = "disable"
