version: '3.7'
services:
#===============STORAGE==============#
  calendar_postgres:
    image: postgres:14
    container_name: calendar-postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB:  ${DB_DATABASE}
    ports:
      - "6543:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${DB_DATABASE} -U ${DB_USERNAME}" ]
      timeout: 45s
      interval: 10s
      retries: 10
    networks:
      calendar:
#====================================#

#===========MESSAGE QUEUE============#
  calendar_mq:
    image: rabbitmq:3-management
    container_name: calendar-mq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 20s
      retries: 5
    restart: on-failure
    networks:
      calendar:
#====================================#
#====================================#
  migrator:
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: "postgres://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:6543/${DB_DATABASE}?sslmode=disable&search_path={DB_SCHEMA}" 
    depends_on:
        calendar_postgres:
          condition: service_healthy

  calendar:
    environment:
      APP_DATABASE_PASSWORD: ${DB_PASSWORD}
      APP_DATABASE_HOST: ${DB_HOST}
    depends_on:
      calendar_postgres:
        condition: service_healthy

  sender:
    environment:
      RMQ_HOST: calendar-mq
    depends_on:
      calendar_mq:
        condition: service_healthy
  
  scheduler:
    environment:
      DATABASE_PASSWORD: ${DB_PASSWORD}
      DATABASE_HOST: ${DB_HOST}
      RMQ_HOST: calendar-mq
      DURATION: ${DURATION}
    depends_on:
      calendar_postgres:
        condition: service_healthy
      calendar_mq:
        condition: service_healthy

#====================================#
networks:
  calendar:
    driver: bridge

volumes:
  postgres_data: